// TradeBot wiki — plain-language manual for operators with no market background.
// Each section: { id, title, group, body: [blocks] }. Block types: p (paragraph), h (sub-heading), ul (bullets),
// table ({cols, rows}), tip, warn, kv (term/definition pairs).

export const GROUPS = ["Start here", "Market basics", "Trading concepts", "How the bot thinks", "The screens", "Gates", "Exits", "Doctor & safety", "Manual trading", "Playbooks", "Reference"];

export const SECTIONS = [
  {
    id: "what-is-tradebot", group: "Start here", title: "What TradeBot is (and is not)",
    body: [
      { t: "p", v: "TradeBot watches brand-new tokens being launched on two networks — Pump.fun on Solana (SOL) and the PONS launchpad on Robinhood Chain (RH) — and tries to buy the few that are attracting real money, then sell them for a small profit before the crowd leaves. It trades tiny amounts (micro-stakes: cents to a few dollars) and makes many trades, so no single trade matters much." },
      { t: "p", v: "It is a rules engine, not a prediction engine. Every buy has to pass a list of measurable checks (the GATES), and every sell is triggered by a measurable rule (the EXITS). When you 'tune the bot' you are moving those thresholds — nothing else." },
      { t: "ul", v: [
        "PAPER mode: the bot pretends to trade using real live prices. No money moves. Use this to learn and to let the Doctor collect statistics.",
        "LIVE mode: real transactions from the wallet shown in the header. Only flip this after weeks of paper results you understand.",
        "Two chains, two books: SOL positions (scalp / hunt / runner / ladder) and RH positions (rh_pons). They have separate slots, separate gates and separate switches.",
      ] },
      { t: "warn", v: "Most new tokens go to zero within minutes. The bot expects to lose on many trades; the edge comes from cutting losers fast (small −R) and letting the rare winners run (+2R, +3R…). If you loosen gates to 'get more trades' you almost always add losers, not winners." },
    ],
  },
  {
    id: "first-10-minutes", group: "Start here", title: "Your first 10 minutes",
    body: [
      { t: "ul", v: [
        "1 · Header: the green/amber pill tells you if the bot is RUNNING and whether the Live Doctor has benched a book. 'PAPER MODE' means nothing is real.",
        "2 · KPI strip (LIVE tab): wallet, P/L today, harvest/search split, drawdown, SLOTS (open positions / max), feed health, TEMPO and DOC (Doctor stance).",
        "3 · ACTIVE TRADES: what is open right now, its unrealized P/L, its stage in the exit ladder, and a ✕ to sell manually.",
        "4 · CANDIDATES: tokens the scanner is tracking. 'gate ✓ · buy' = it passes the pre-rank; the row's gate text tells you what is still blocking an automatic entry.",
        "5 · SKIP TICKER (bottom): a live stream of why the bot did NOT buy. This is the single best place to learn what the gates are doing.",
        "6 · CONTROL tab: every switch and threshold. Switches (feeds, scanner, paper/live) apply instantly; number fields apply when you press Save.",
      ] },
      { t: "tip", v: "Leave everything at defaults for at least a day in PAPER mode. Watch the skip ticker and the Doctor's cost table before touching a single gate." },
    ],
  },
  {
    id: "launch-lifecycle", group: "Market basics", title: "How a new token is born: the bonding curve",
    body: [
      { t: "p", v: "On Pump.fun and PONS a creator launches a token with zero liquidity. Instead of a normal exchange there is a BONDING CURVE: a smart contract that sells tokens at a price that rises mechanically as more SOL/ETH is paid in, and falls as people sell back. Early buyers get a lower price; every later buyer pushes the price (and the market cap) up." },
      { t: "kv", v: [
        ["Curve fill %", "How far the curve is toward its cap. 0% = just launched, 100% = about to graduate."],
        ["Graduation / sweep", "When the curve fills, the contract moves the raised SOL/ETH plus tokens into a real exchange pool (PumpSwap on Solana, a Uniswap v4 pool on RH). Trading continues there with normal supply-and-demand pricing."],
        ["Pool", "The post-graduation market. 'Pool liquidity' is how much money sits in it — the more liquidity, the less your own trade moves the price."],
        ["Market cap (MC)", "Price × total supply. A $30K MC token with 1 billion supply trades at $0.00003. The bot uses MC bands to know which kind of token it is looking at."],
        ["Seasoned vs new", "NEW = still on the curve, minutes old. SEASONED = already graduated, priced on the pool. They get different gates because they behave differently."],
      ] },
      { t: "p", v: "Why it matters: on the curve, price only moves when someone trades. A token with no trades for 20 seconds is dead until proven otherwise — that is why several gates look at 'last trade age' and 'new buyers in the last minute'." },
    ],
  },
  {
    id: "flow-and-participants", group: "Market basics", title: "Who is on the other side: buyers, sellers, creators, snipers",
    body: [
      { t: "kv", v: [
        ["Unique buyers / holders", "Distinct wallets that bought. Ten different wallets buying $5 is healthier than one wallet buying $50 — real interest is spread out."],
        ["Inflow", "Net money entering the curve/pool over a window (buys minus sells). Positive inflow = the price has fuel."],
        ["Velocity / momentum", "How fast price or MC is changing right now (e.g. +5% in the last 30s). The bot only buys into things that are already moving."],
        ["Creator / deployer", "The wallet that launched the token. Serial creators who launch dozens of tokens that never graduate are a red flag (serial-creator gate). A creator dumping their own bag is a rug signal."],
        ["Sniper", "A bot that buys in the first second of a launch. Snipe-tax windows and 'min age' gates keep us from paying the sniper's exit."],
        ["Rug / dump", "The creator or a whale sells everything at once and the price collapses. The RH rug detector watches for a single sell above a size/percentage and exits immediately."],
        ["Flush", "A single wallet (or two) dumping while buyers are still stepping in. Looks like a crash for a few seconds, then recovers. The flush hold waits it out instead of panic selling."],
        ["Distribution", "Many different wallets selling into strength — the crowd is leaving. Not a flush; the bot exits."],
      ] },
    ],
  },
  {
    id: "costs", group: "Market basics", title: "Costs: fees, slippage, priority, gas",
    body: [
      { t: "p", v: "Every round trip (buy then sell) costs money before the price moves at all. The bot's COST GATE refuses trades whose expected cost is more than about half of the first profit target, because you would need the token to rise just to get back to zero." },
      { t: "kv", v: [
        ["Protocol fee", "Pump.fun / PONS take ~1% per trade on the curve; pools have their own fee tier."],
        ["Slippage", "The gap between the price you saw and the price you got. Thin (low-liquidity) curves move a lot on a small order. 'Slippage bps' is the maximum you allow (100 bps = 1%). Too tight → the transaction fails; too loose → you overpay."],
        ["Priority fee (SOL) / gas (RH)", "What you pay validators to include your transaction quickly. Speed mode presets bundle priority + slippage. On dumps the bot widens both (panic tier) because landing the sell matters more than the cents."],
        ["Fee drag", "Fees as a % of stake. A $0.50 trade paying $0.03 round trip has 6% drag — a big handicap. That is why min_trade_usd exists."],
      ] },
    ],
  },
  {
    id: "position-and-risk", group: "Trading concepts", title: "Position size, stop loss, R and why everything is measured in R",
    body: [
      { t: "p", v: "R is the amount you are willing to lose on one trade. If you buy $1.00 of a token with a 12% stop loss, R = $0.12. A trade that closes at +$0.24 is a '+2R' trade; one that stops out is '−1R'. Measuring in R lets you compare a $0.50 scalp and a $5 RH trade on the same scale." },
      { t: "kv", v: [
        ["Stop loss (SL)", "Sell if the price falls this % below entry. The bot's hard floor. Slippage is added to it ('SL% with slip') so 1R reflects what you actually lose."],
        ["Take profit (TP) / target R", "Sell (or sell part) at this gain. Scalp targets 1.5R, hunt 2R. A target in R adapts automatically when you change the SL."],
        ["Trailing stop", "Once armed, the stop follows the peak: sell when the price gives back X% from its high. Lets winners run while locking in gains. The RATCHET tightens the trail as the gain grows."],
        ["Breakeven stop", "After a ladder leg or +1R, the stop moves up to entry + exit costs so the trade can no longer become a loser."],
        ["Partial / ladder leg", "Selling part of the position at +1R and +2R (hunt book) — banks money while keeping a runner."],
        ["MFE / peak", "Maximum favourable excursion — the best the trade ever looked. A trade that never reaches +5% MFE in 30s is 'no momentum' and gets flattened."],
        ["Drawdown (DD)", "How far the equity curve has fallen from its high. DD 24H on the KPI strip is today's damage."],
        ["Payoff / expectancy", "Average win ÷ average loss (after fees). Below 1.0 over a sample means the book is losing — the Live Doctor benches it."],
      ] },
      { t: "tip", v: "Sizing is automatic: the bot picks the stake so that a stop-out costs about the same R in dollars on every trade, scaled by book, regime and Doctor stance. You control the rails (min/max trade $), not each trade." },
    ],
  },
  {
    id: "search-vs-harvest", group: "Trading concepts", title: "Search capital vs harvest capital",
    body: [
      { t: "p", v: "The bot splits its bankroll into two mental accounts. SEARCH capital pays for the many small, fast, mostly-losing probes that find a winner (scalp entries, snipes). HARVEST capital is what the winners earn once promoted to hunt/runner ladders. The KPI 'harvest / search' shows both; a healthy day has search slightly negative and harvest clearly positive." },
      { t: "ul", v: [
        "search_budget_pct (default 40%) caps how much of the day's risk budget the search side may burn.",
        "'search ledger: remaining $' in the logs / Doctor is how much probing budget is left today. When it is gone, only re-entries and promotions continue.",
        "Cost per runner = search dollars spent per winner found. The Doctor uses it to decide whether the search is worth continuing in the current market tempo.",
      ] },
    ],
  },
  {
    id: "pipeline", group: "How the bot thinks", title: "The pipeline: feed → tracking → candidates → gates → entry → exits",
    body: [
      { t: "ul", v: [
        "FEED · One websocket per chain streams every launch and trade. SOL: the shared Solana socket (Pump.fun program logs + per-position account pushes). RH: the sequencer feed. If a feed is down nothing downstream can happen — check the SOL FEED / RH FEED cells first.",
        "TRACKING · Every launch gets a 'bucket': price path, buyers, inflow, curve fill, creator history. Buckets age out (band windows) so memory stays bounded.",
        "CANDIDATES (pre-rank) · Every scanner tick (scanner_interval_s, 15s) the scanner scores buckets by growth, inflow and new buyers and shows the closest ones. 'passes' = cleared the pre-rank thresholds. This is only a shortlist.",
        "GATES (entry decision) · For each passing candidate the bot runs the full gate list — liquidity, buyers, age, MC, velocity, classifier, creator, cost, slots, Doctor breakers. The first failing gate is what you see in the row and in the skip ticker.",
        "ENTRY · Size is computed (R sizing, book, regime, Doctor multiplier), slippage/priority chosen by speed mode, and the buy is sent (or simulated with real latency in paper).",
        "BOOK · The position is assigned to a book — scalp (fast, 40s clock), hunt (ladder legs), runner (promoted winner, no clock), ladder (graduate ladder), rh_pons (RH curve) — which decides its exit rules.",
        "EXITS · Every tick (and every pushed trade on the position's curve/pool) the exit ladder is evaluated: SL, TP, trail, no-momentum, dead tape, clock, rip-cords, flush hold, momentum gate.",
        "DOCTOR · Every closed trade feeds the Live Doctor, which adjusts sizes/gates by tempo, arms breakers when a book's payoff drops below 1.0 after fees, and proposes tuning.",
      ] },
    ],
  },
  {
    id: "books", group: "How the bot thinks", title: "Books: scalp, hunt, runner, ladder, rh_pons",
    body: [
      { t: "table", cols: ["Book", "What it is", "Default exits"], rows: [
        ["scalp (SOL)", "Fast probe on a NEW curve showing momentum. Search capital.", "SL 12% · target 1.5R · trail 6% armed at +12% · clock 40s"],
        ["hunt (SOL)", "Bigger, pattern-backed entry (greylist snipe, second impulse). Ladder partials.", "SL 20% · +1R sell 35% · +2R sell 30% · trail 8% · no clock"],
        ["runner (SOL)", "A scalp/hunt winner promoted after banking a leg. Rides the trend.", "SL 25% from promotion · giveback trail 15% armed at +1R · +3R bank 25% · exits when flow dies (unless manual)"],
        ["ladder (SOL)", "Graduate Ladder: a graduated token climbing MC steps; each step is a leg with its own ratchet trail.", "structure stop closes every leg · half size (ladder_size_mult)"],
        ["rh_pons (RH)", "PONS curve entries on Robinhood Chain. Paper by default; live needs rh_live_trading.", "SL 12% · TP 20% (or target R) · trail 6% armed at +12% · clock 35s · graduated-while-held → R-trail ride (no TP, no clock)"],
      ] },
      { t: "p", v: "Book exits are editable per book under BOOKS → book exits, and the Doctor may tune them within its grid (SL 8–30%, target 1–3R)." },
    ],
  },
  {
    id: "screens", group: "The screens", title: "Tab by tab",
    body: [
      { t: "kv", v: [
        ["LIVE", "The cockpit. KPI strip · Active trades (auto on top, manual holds below the divider) · Equity chart by book · Candidates with Buy Now · Graduate Ladder · Doctor strip · Skip ticker."],
        ["SCAN", "Raw launch feed and tracked tokens, greylist (pattern memory of creators and snipes), skip reasons in detail."],
        ["LADDER", "Graduate Ladder full list: MC steps, pinned manual tokens, holding status."],
        ["DOCTOR", "Live Doctor: per-book cost table, breakers and when they lift, tempo, autopsy of closed trades (why each lost or won), proposals and Autopilot."],
        ["BOOKS", "P/L by source, scorecard cells (situation × outcome), classifier verdicts, book exit ladders."],
        ["CONTROL", "Bot control: start/stop, paper/live, feeds, scanner, speed mode, sizing rails, every gate, RH section, wallets, kill switches."],
        ["WIKI", "This manual."],
      ] },
      { t: "h", v: "Reading a candidate row" },
      { t: "p", v: "BAND (new / seasoned / rh_new) · SYMBOL with chain badge · GROWTH since first seen · GATE. Green 'gate ✓ · buy' = pre-rank passed; click it to buy at standard size as a manual hold. Grey 'gate: liquidity 0.01 SOL < 9.5' = the exact gate blocking an automatic entry right now, with the measured value vs the threshold." },
      { t: "h", v: "Reading the skip ticker" },
      { t: "p", v: "Each item is SYMBOL | REASON. Reasons map 1:1 to gates: edge/age, liquidity, buyers, growth, inflow, velocity, classifier skip, serial creator, cost gate, max positions, doctor-breaker:<book>, regime-dead, sl-cooldown. If one reason dominates for hours, that is the gate to look at — either the market is genuinely quiet or the threshold is too strict for today's tempo." },
    ],
  },
  {
    id: "gates-sol", group: "Gates", title: "Solana entry gates (CONTROL → gates)",
    body: [
      { t: "p", v: "A gate is a yes/no check. Loosening (lower minimums, higher maximums) lets more tokens through — more trades, lower quality. Tightening does the opposite. Change ONE gate at a time and give it a few hours of paper trading before judging." },
      { t: "table", cols: ["Gate (field)", "Default", "What it checks", "If you loosen it…"], rows: [
        ["min_curve_liquidity_sol / _new", "12 / 20 SOL", "SOL sitting in the curve. Thin curves = huge slippage both ways.", "cheaper fills on paper, ugly fills live; more rugs"],
        ["min_buyers_for_entry / _new", "3 / 8", "Distinct wallets that bought.", "more one-whale tokens that dump on you"],
        ["scanner_min_growth_pct / _new", "20% / 50%", "Price growth over the lookback since first seen.", "buys before momentum is proven; more dead entries"],
        ["scanner_min_recent_inflow_sol / _new", "3 / 5 SOL", "Net SOL into the curve over scanner_recent_inflow_window_s (5 min).", "buys tokens nobody is funding"],
        ["scanner_min_new_buyers / _new", "5 / 10", "New buyers in scanner_holder_velocity_window_s (60s).", "slower tapes qualify; more no-momentum exits"],
        ["scanner_entry_velocity_min_pct", "0 (Doctor sets ~3.5)", "Price change over the last scanner_entry_velocity_window_s (30s) at the moment of entry.", "enters flat tapes — the #1 source of −1R scalps"],
        ["band_new_max_age_min / band_seasoned_max_age_min", "15 / 60 min", "How old a token may be and still be in the NEW / SEASONED band.", "chases older tokens whose early buyers are looking for an exit"],
        ["scanner_min_mc_usd_seasoned", "$30K", "MC floor for graduated tokens.", "dust-cap pools with no depth"],
        ["scanner_min_mc_velocity_5m_pct_seasoned", "+5%", "MC change over 5 min for seasoned entries.", "enters drifting pools"],
        ["serial_creator_min_launches / requires_graduation", "3 / on", "Creator launched ≥N tokens before; skip unless one graduated.", "more farm tokens from professional ruggers"],
        ["creator_solvency (creator_sol_min)", "0.5 SOL", "Creator wallet keeps at least this much SOL (skin in the game).", "more throwaway launches"],
        ["max_concurrent_positions", "3 (max 8)", "Open SOL positions that count (manual holds don't).", "more simultaneous risk, thinner attention per position"],
        ["min_trade_usd / max_trade_usd", "$0.50 / $1.00", "Sizing rails. R sizing picks the stake inside these.", "bigger stakes = bigger slippage on thin curves"],
        ["regime_dead_blocks_search", "on", "When launches/h fall below regime_dead_rate_h (8), pause search entries.", "keeps probing a dead market and pays fees for nothing"],
      ] },
      { t: "h", v: "Gates you cannot see as numbers" },
      { t: "ul", v: [
        "Classifier: a pattern model over the bucket (buyers, inflow shape, creator history) that returns enter / skip / abort. 'classifier skip' in the ticker.",
        "Cost gate: expected slippage + fees for THIS size on THIS curve must be ≤ ~half the first target. 'cost gate' skips get more common on thin curves and bigger stakes.",
        "Scorecard: situation cells (band × regime × pattern) with a losing record are disabled by the Doctor.",
        "Doctor breakers: a benched book refuses live entries; on paper it trades at ×0.5 size with gates ×1.25.",
        "SL cooldown: a token that stopped you out is locked for sl_cooldown_minutes (5).",
      ] },
    ],
  },
  {
    id: "gates-rh", group: "Gates", title: "Robinhood Chain (RH PONS) gates",
    body: [
      { t: "table", cols: ["Field", "Default", "Meaning"], rows: [
        ["rh_feed_enabled / rh_paper_enabled / rh_live_trading", "on / off / off", "Feed must be on to see anything; paper must be on to trade on paper; live sends real ETH."],
        ["rh_max_positions", "3", "Open RH positions that count (manual holds excluded)."],
        ["rh_min_age_s / rh_max_age_min", "5s / 15min", "Skip the sniper window; skip stale launches."],
        ["rh_min_growth_pct / rh_max_growth_pct", "30% / 400%", "Must have moved, but not already 5×  ('chased')."],
        ["rh_min_new_buyers_1m / rh_min_unique_buyers", "5 / 8", "Buyers in the last minute / since launch."],
        ["rh_min_inflow_usd", "$300", "Net quote into the curve over the inflow window (ETH/USDG quotes)."],
        ["rh_min_curve_pct / rh_max_curve_pct", "5% / 70%", "Not too early, and not right before the graduation sweep gap."],
        ["rh_min_mc_usd / rh_max_mc_usd", "$5K / $60K", "MC band for curve entries."],
        ["rh_max_last_trade_age_s", "20s", "Curve must have printed recently."],
        ["rh_seasoned_max_age_min", "60 min", "Post-graduation entries allowed this long after the sweep."],
        ["rh_rug_sell_usd / rh_rug_sell_curve_pct", "$300 / 15%", "A single sell this big on a held curve = exit now."],
        ["rh_grad_handoff_r_trail / rh_grad_trail_r", "on / 1.0R", "Graduated while held → ride the pool on an R trail: no fixed TP, stop → breakeven+costs after +1R, exit on a 1R giveback from the peak."],
        ["rh_max_trade_usd / rh_fee_drag_max_pct", "$5 / 5%", "Stake rail and the maximum share gas may eat."],
        ["rh_daily_kill_switch_usd / rh_gas_reserve_eth", "$20 / 0.002", "Live loss today that auto-disables live RH; ETH never spent (exits need gas)."],
      ] },
    ],
  },
  {
    id: "exits", group: "Exits", title: "Every way a position can close",
    body: [
      { t: "table", cols: ["Exit", "Trigger", "Notes"], rows: [
        ["stop-loss", "P/L ≤ −SL% (persisted for sl_persistence_ms with ≥2 samples)", "Hard floor. Momentum gate may defer up to exit_momentum_max_defer_s (20s) while ≥3 buyers keep buying, never beyond an extra 5% loss."],
        ["take-profit / target", "P/L ≥ target R × SL%", "Scalp cash-out. Hunt sells a leg instead."],
        ["trailing-stop", "giveback from peak ≥ trail% once armed", "Ratchet tiers tighten the trail as the peak grows."],
        ["ladder leg (+1R / +2R)", "hunt: sell 35% / 30%", "Stop moves to breakeven + exit costs after each leg."],
        ["no_momentum", "after no_momentum_after_s (30s) the peak never reached no_momentum_min_mfe_pct (5%)", "Flattens dead entries. Never applies to manual holds."],
        ["scalp clock / max_hold", "hold_max_seconds (scalp 40s, rh_pons 35s)", "Search probes are not investments. Runner and manual holds have no clock."],
        ["search-dead-tape", "no new buyer and no inflow for no_new_buyers_s", "Off by default (0)."],
        ["snipe rip-cords", "pattern broke / drawdown / velocity decay on greylist snipes", "Hunt-book specific. Manual holds exempt."],
        ["runner-exhausted / giveback", "flow died or 15% giveback from peak (armed +1R)", "Runner only."],
        ["rug_detected (RH)", "single sell ≥ $300 or ≥15% of curve reserves", "Bypasses the momentum gate."],
        ["r_trail / r_trail_stop (RH)", "graduated-while-held ride: 1R giveback from peak / breakeven+costs stop", "No fixed TP, no clock."],
        ["daily kill switch", "realised loss today ≥ daily_kill_switch_usd ($20)", "Bot disables itself. Reset from CONTROL."],
        ["manual", "✕ on the row / detail drawer", "Always honoured, even mid-graduation."],
      ] },
      { t: "h", v: "Holds that delay an exit on purpose" },
      { t: "ul", v: [
        "Buy-momentum gate: a SL/TP that fires while ≥ exit_momentum_min_buyers distinct wallets are still buying (and inflow > outflow) is deferred up to 20s, bounded by a hard extra-loss floor. Stops you from selling into the dip right before the next leg.",
        "Flush hold: on a SL/trail trigger, forensics look at who sold since the peak. ≤2 sellers with one holding ≥70% of the sold amount and ≥1 buyer stepping in = a flush, not distribution → hold up to flush_hold_s (10s) with a flush_extra_drop_pct (5%) floor under the trough. Scope: hot/re-entry positions by default, or all.",
        "Graduation: never an exit. The venue flips to the pool, any curve-priced trigger in flight is dropped, and the gates re-evaluate on pool prices (RH hands the position to the R-trail ride).",
      ] },
    ],
  },
  {
    id: "doctor", group: "Doctor & safety", title: "The Live Doctor, breakers, tempo and Autopilot",
    body: [
      { t: "p", v: "The Live Doctor is the bot's risk manager. It reads every closed trade and does four things:" },
      { t: "ul", v: [
        "COST TABLE · per book: fees, slippage, latency, payoff after fees over the last 4h. Payoff < 1.0 with enough samples arms a BREAKER.",
        "BREAKERS · a benched book (amber strip: 'SCALP paused by live-doctor breaker · resumes in 3h') refuses LIVE entries. On paper it keeps trading at ×0.5 size with gates ×1.25 so the statistics keep flowing. Click LIFT to override.",
        "TEMPO · launches/hour and fill quality scale the gates: slow tape → lower momentum expectations; hot tape → higher. 'TEMPO 1×' on the KPI strip is neutral.",
        "PROPOSALS / AUTOPILOT · the autopsy classifies every loss (rugged, chased, fee_drag, dead_entry, stopped_then_ran, gave_back…) and proposes one-notch changes to specific gates. With Autopilot ON it applies them within its grid and can revert.",
      ] },
      { t: "kv", v: [
        ["doctor_pause / stance", "DOC cell on the KPI strip: adjust = trading normally with tempo scaling; benched = one or more books paused."],
        ["Kill switches", "daily_kill_switch_usd (SOL) and rh_daily_kill_switch_usd (RH live). When tripped the bot stops taking entries until you reset it."],
        ["Graceful stop", "STOP = no new entries, open positions ride to their exits. Use it instead of hard-closing."],
        ["Inventory halt", "Too many unpriced/held bags → no new entries until they resolve."],
      ] },
    ],
  },
  {
    id: "manual", group: "Manual trading", title: "Buy Now, manual tokens and manual holds",
    body: [
      { t: "ul", v: [
        "BUY NOW · click the green 'gate ✓ · buy' on a candidate. Standard sizing, current speed mode, marked as a MANUAL HOLD.",
        "ADD MANUAL TOKEN · LADDER → add a mint / RH address. The token is pinned to the Graduate Ladder regardless of age/MC and can be bought from there.",
        "MANUAL HOLD rules · SL, TP and trailing stop still apply. NOT applied: no-momentum kill, rip-cords, velocity exits, runner flow-death, hold clock, dead-tape stop. Manual holds do not consume a slot (SLOTS shows them as +N) and are listed under the 'manual holds' divider in Active Trades.",
        "MANUAL EXIT · ✕ on the row or 'sell' in the token drawer. Always executes, including through a graduation.",
      ] },
      { t: "warn", v: "A manual hold has no clock: if you forget it, the only thing protecting you is the stop loss. Check the Active Trades list before walking away." },
    ],
  },
  {
    id: "playbook-quiet", group: "Playbooks", title: "Playbook: 'the bot isn't trading'",
    body: [
      { t: "ul", v: [
        "1 · Header pill says RUNNING? If not, press START. If it says BENCHED, read the amber strip — paper still trades, live doesn't.",
        "2 · SOL FEED / RH FEED cells green? Red = websocket down; the status text tells you why (rejected handshake, quota, switch OFF). The shared Solana socket fails over to the paid endpoint automatically.",
        "3 · CANDIDATES shows an amber 'SOL SCANNER OFF' banner? Click 'turn on'. Without the scanner, green ✓ rows are never auto-entered.",
        "4 · SLOTS full (3/3)? Wait or raise max_concurrent_positions. Manual holds don't count.",
        "5 · Skip ticker: what reason dominates? 'regime-dead' = market is quiet (fewer than regime_dead_rate_h launches/hour). 'entry_velocity' = tapes are flat. 'doctor-breaker' = live entries benched. 'cost gate' = curves too thin for your stake.",
        "6 · Still nothing? DOCTOR tab → cost table and search ledger. If 'remaining $' is negative the search budget for today is spent.",
      ] },
    ],
  },
  {
    id: "playbook-tuning", group: "Playbooks", title: "Playbook: adjusting a gate safely",
    body: [
      { t: "ul", v: [
        "Write down the current value and today's paper P/L, win rate and payoff (BOOKS tab).",
        "Change one field by one notch (e.g. min_buyers 8 → 6). Press Save. Watch the skip ticker: the reason you targeted should shrink and other reasons should take over.",
        "Give it 4+ hours or 30+ trades. Compare payoff after fees and the autopsy causes. More 'dead_entry' or 'rugged' = you loosened the wrong gate.",
        "Prefer letting the Doctor propose. Its proposals come with the evidence (n, $ share) and stay inside a safe grid.",
        "Never loosen liquidity and buyers gates at the same time as raising stake size — slippage compounds.",
      ] },
    ],
  },
  {
    id: "playbook-live", group: "Playbooks", title: "Playbook: before going live",
    body: [
      { t: "ul", v: [
        "Two weeks of paper with positive payoff after fees on the book you want to arm.",
        "Fund the wallet with only what you can lose. The bot never spends below the gas/priority reserve, but every trade can go to zero.",
        "Keep max_trade_usd tiny at first ($1) — live slippage on thin curves is worse than paper's model.",
        "Set daily_kill_switch_usd to a number you are comfortable losing in a bad day. It is the last line of defence.",
        "Arm ONE chain at a time (live_trading for SOL, rh_live_trading for RH). Watch the first 20 fills against their paper twins (PAPER_FILL vs real slippage in the logs / Doctor).",
      ] },
    ],
  },
  {
    id: "glossary", group: "Reference", title: "Glossary A–Z",
    body: [
      { t: "kv", v: [
        ["Band", "Which age/venue bucket a token is in: new (curve), seasoned (pool), rh_new (RH curve)."],
        ["Bonding curve", "Contract that prices a new token mechanically by how much has been paid in."],
        ["bps", "Basis points. 100 bps = 1%."],
        ["Breaker", "Live Doctor pause on a book whose payoff after fees fell below 1.0."],
        ["Bucket", "The bot's in-memory record of one token's price path, buyers and inflow."],
        ["Chased", "Entering after the price already ran far — you become early buyers' exit liquidity."],
        ["Classifier", "Pattern model that returns enter/skip/abort for a candidate."],
        ["Cost gate", "Refuses trades whose fees+slippage exceed ~half the first target."],
        ["Curve fill %", "Progress of the bonding curve toward graduation."],
        ["DAS / Helius", "Solana data provider used for holder counts and the paid websocket fallback."],
        ["Dead tape", "No new buyers and no inflow for a while."],
        ["Distribution", "Many wallets selling — the crowd leaving. Opposite of a flush."],
        ["Drawdown", "Fall from the equity high."],
        ["Fast fail add", "RH: doubling into a position that immediately confirms (second half of the stake)."],
        ["Flush", "One or two wallets dumping while buyers still step in; usually recovers."],
        ["Graduation / sweep", "Curve completes; liquidity moves to a real pool."],
        ["Greylist", "Memory of creators/snipe patterns with their outcomes."],
        ["Harvest / search", "Capital earned by winners vs capital spent probing for them."],
        ["Hot symbol", "A token that already paid ≥ hot_token_pnl_pct (25%) — re-entries get priority and ×1.5 size."],
        ["Inflow", "Net money entering (buys − sells) over a window."],
        ["Ladder", "Staged partial exits at R multiples; also the Graduate Ladder MC staircase."],
        ["Liquidity", "Money in the curve/pool that absorbs your trade."],
        ["MC", "Market cap = price × supply."],
        ["MFE", "Max favourable excursion — the best unrealized gain a trade reached."],
        ["Momentum gate", "Defers an exit while buyers keep buying."],
        ["No-momentum exit", "Flatten a position that never moved after 30s."],
        ["Paper", "Simulated trading on live prices with modelled latency and slippage."],
        ["Payoff", "Average win ÷ average loss after fees."],
        ["Pinned", "A manually added token kept on the ladder regardless of gates."],
        ["Priority fee", "Solana tip for faster inclusion."],
        ["Promotion", "A scalp/hunt winner becoming a runner after banking a leg."],
        ["R", "Risk unit: the dollar loss at the stop."],
        ["Ratchet trail", "Trailing stop that tightens as the gain grows."],
        ["Regime", "Market state by launches/hour: dead / quiet / busy / hot."],
        ["Rip-cord", "Fast pattern-based exit for snipes (drawdown, velocity decay, pattern broke)."],
        ["Rug", "Creator/whale dumps everything; price collapses."],
        ["Runner", "Promoted winner with no clock, trailing from the peak."],
        ["Scorecard", "Situation × outcome table; losing cells are disabled."],
        ["Seasoned", "Already graduated; priced on the pool."],
        ["Serial creator", "Deployer with many prior launches; gated."],
        ["Slippage", "Difference between expected and executed price."],
        ["Slot", "One of max_concurrent_positions. Manual holds don't use one."],
        ["Snipe", "Buying in the first seconds of a launch."],
        ["Speed mode", "Preset bundling priority fee + entry/exit slippage."],
        ["Tempo", "Doctor's market-speed multiplier applied to gates."],
        ["Trailing stop", "Stop that follows the peak."],
        ["Venue", "Where a position is priced: curve or pool."],
        ["WSS", "WebSocket feed connection."],
      ] },
    ],
  },
];
